-- H2 용 스키마. PostgreSQL 판과 한 군데만 다르다.
-- H2 에는 길이 없는 varchar 가 없어 payload 에 상한을 준다.
-- 벤더별 폴더로 나눈 이유가 이 한 줄이다. 하나로 합치려다 타입이 미묘하게 어긋나면
-- ddl-auto=validate 가 부팅을 막는다.

-- 수집 큐. 상품 1건에 대한 수집 작업이자 상태 기계.
create table collect_job (
    id            bigint generated by default as identity primary key,
    site_code     varchar(32)   not null,
    external_id   varchar(128)  not null,
    source_url    varchar(1024) not null,
    status        varchar(16)   not null,
    attempt       integer       not null,
    max_attempts  integer       not null,
    next_run_at   timestamp(6) with time zone not null,
    worker_id     varchar(64),
    leased_until  timestamp(6) with time zone,
    last_error    varchar(1000),
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    version       bigint        not null,
    constraint uk_job_dedup unique (site_code, external_id)
);

-- 같은 상품을 두 번 큐에 넣지 않기 위한 멱등 키는 위 유니크 제약이 담당한다.
-- 아래 두 인덱스는 큐를 도는 두 가지 조회를 위한 것이다.
create index ix_job_poll  on collect_job (status, next_run_at);  -- 클레임 후보 찾기
create index ix_job_lease on collect_job (status, leased_until); -- 죽은 워커 회수

-- 수집 원본. 정규화 규칙이 바뀌어도 다시 돌릴 수 있도록 그대로 남긴다.
create table raw_product (
    id           bigint generated by default as identity primary key,
    job_id       bigint      not null,
    site_code    varchar(32) not null,
    payload      varchar(32600) not null,
    collected_at timestamp(6) with time zone not null
);

create index ix_raw_job on raw_product (job_id);

-- 정규화된 상품. 사이트별 원본 구조 차이를 여기서 흡수한다.
create table product (
    id             bigint generated by default as identity primary key,
    site_code      varchar(32)   not null,
    external_id    varchar(128)  not null,
    title          varchar(500)  not null,
    price_amount   numeric(15,2) not null,
    currency       varchar(3)    not null,
    main_image_url varchar(1024),
    source_url     varchar(1024) not null,
    collected_at   timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    constraint uk_product_source unique (site_code, external_id)
);

create table product_option (
    id             bigint generated by default as identity primary key,
    product_id     bigint       not null,
    option_name    varchar(100) not null,
    -- VALUE 는 예약어라 컬럼명을 분리한다
    option_value   varchar(200) not null,
    extra_price    numeric(15,2),
    stock_quantity integer,
    image_url      varchar(1024),
    constraint fk_option_product foreign key (product_id) references product (id)
);

create index ix_option_product on product_option (product_id);

-- 오픈마켓 등록 큐. 상품 1건을 마켓 1곳에 올리는 등록 건.
create table market_listing (
    id                bigint generated by default as identity primary key,
    product_id        bigint      not null,
    market_code       varchar(32) not null,
    status            varchar(16) not null,
    market_product_id varchar(128),
    payload_hash      varchar(64),
    attempt           integer     not null,
    max_attempts      integer     not null,
    next_run_at       timestamp(6) with time zone not null,
    sent_at           timestamp(6) with time zone,
    last_error_code   varchar(40),
    last_error        varchar(1000),
    listed_at         timestamp(6) with time zone,
    created_at        timestamp(6) with time zone not null,
    updated_at        timestamp(6) with time zone not null,
    version           bigint      not null,
    constraint uk_listing_target unique (product_id, market_code)
);

-- 등록 건은 상품보다 오래 남는다(상품이 지워져도 무엇을 왜 못 올렸는지는 남아야 한다).
-- 그래서 product 로의 외래키를 걸지 않는다.
create index ix_listing_dispatch on market_listing (status, next_run_at); -- 전송 차례 찾기
create index ix_listing_stuck    on market_listing (status, sent_at);     -- 응답 없는 전송 회수
